# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: A Sky Full of Stars
subtitle: ''
description: 'Expected losses are losses but expected gains are not gains.'
keywords:
author: Chn Xen
language: zh-CN
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
#include:
#exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: ''


# ===============================================================
# Theme Settings Section
# ===============================================================
theme_config:

  # ---------------------------------------------------------------
  # Theme Core Configuration Settings
  # See: https://theme-next.org/docs/theme-settings/
  # ---------------------------------------------------------------
  reminder: true
  minify: true

  # ---------------------------------------------------------------
  # Site Information Settings
  # ---------------------------------------------------------------
  language_switcher: true

  # ---------------------------------------------------------------
  # Scheme Settings
  # ---------------------------------------------------------------
  scheme: Pisces
  darkmode: true

  # ---------------------------------------------------------------
  # Menu Settings
  # ---------------------------------------------------------------

  # Usage: `Key: /link/ || icon`
  menu:
    home: / || home
    categories: /categories/ || th
    schedule: /schedule/ || calendar
    archives: /archives/ || archive
    #about: /about/ || user
    tags: /tags/ || tags
    #sitemap: /sitemap.xml || sitemap
    #commonweal: /404/ || heartbeat

  # ---------------------------------------------------------------
  # Sidebar Settings
  # See: https://theme-next.org/docs/theme-settings/sidebar
  # ---------------------------------------------------------------
  sidebar:
    position: right

  # Sidebar Avatar
  avatar:
    url: /uploads/avatar.png
    rounded: true
    rotated: false

  # Social Links
  social:
    GitHub: https://github.com/zcoaolas || github
    E-Mail: mailto:zcoaolas@gmail.com || envelope
    Telegram: https://t.me/zcoaolas || telegram
    Twitter: https://twitter.com/zcoaolas || twitter

  social_icons:
    enable: true
    icons_only: true
    transition: true

  toc:
    enable: true
    number: true
    wrap: true
    expand_all: true
    max_depth: 6

  # ---------------------------------------------------------------
  # Custom Page Settings
  # See: https://theme-next.org/docs/theme-settings/custom-pages
  # ---------------------------------------------------------------
  # Google Calendar
  calendar:
    calendar_id: "ii13ubgir4hqnvenp098nge7k4@group.calendar.google.com"
    api_key: "AIzaSyBaII3l_wXZdo3pSfcae80m3VIfd06cvnM"
    offsetMax: 168 # Time Range
    offsetMin: 96 # Time Range
    orderBy: startTime
    showDeleted: false
    singleEvents: true
    maxResults: 250

  # ---------------------------------------------------------------
  # Misc Theme Settings
  # ---------------------------------------------------------------
  custom_logo: /uploads/logo.png
  
  back2top:
    sidebar: true
    scrollpercent: true

  # ---------------------------------------------------------------
  # Favicon config
  # ---------------------------------------------------------------
  favicon:
    small: /images/favicon-16x16.png
    medium: /images/favicon-32x32.png
    apple_touch_icon: /images/apple-touch-icon.png
    safari_pinned_tab: /images/safari-pinned-tab.svg
    ms_browserconfig: /images/browserconfig.xml

  # ---------------------------------------------------------------
  # Animation Settings
  # ---------------------------------------------------------------

  three:
    enable: true
    three_waves: true

  vendors:
    three: //cdn.jsdelivr.net/gh/theme-next/theme-next-three@1/three.min.js
    three_waves: //cdn.jsdelivr.net/gh/theme-next/theme-next-three@latest/three-waves.min.js
  
  # ---------------------------------------------------------------
  # Comments Settings
  # See: https://theme-next.org/docs/third-party-services/comments
  # ---------------------------------------------------------------

  # Valine
  # For more information: https://valine.js.org, https://github.com/xCss/Valine
  valine:
    enable: true
    appid: 7VfiO62J8PDpFohA4kSPszkw-gzGzoHsz
    appkey: Acxvs2zV4cjalnClLR8YxEqo
    notify: true # Mail notifier
    verify: false # Verification code
    placeholder: Any comments? # Comment box placeholder
    avatar: mm # Gravatar style
    guest_info: nick,mail,link # Custom comment header
    pageSize: 10 # Pagination size
    language: # Language, available values: en, zh-cn
    visitor: true # Article reading statistic
    comment_count: true # If false, comment count will only be displayed in post page, not in home page
    recordIP: true # Whether to record the commenter IP
    serverURLs: # When the custom domain name is enabled, fill it in here (it will be detected automatically by default, no need to fill in)
    #post_meta_order: 0
